<?php

namespace FuelPHP\Common;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-23 at 22:34:55.
 */
class HtmlTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var Html
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = Html::forge();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}

	/**
	 * @group common
	 * @covers FuelPHP\Common\Html::forge
	 * @covers FuelPHP\Common\Html::__construct
	 */
	public function testForge()
	{
		
		$this->assertInstanceOf('FuelPHP\Common\Html', Html::forge());
	}

	/**
	 * @covers FuelPHP\Common\Html::tag
	 * @todo   Implement testTag().
	 */
	public function testTag()
	{
		$tag = $this->object->tag('div');
		
		$expected = array(
			'tag' => 'div',
		);
		
		$this->assertTag($expected, $tag);
	}

	/**
	 * @covers FuelPHP\Common\Html::arrayToAttributes
	 */
	public function testArrayToAttributes()
	{
		$this->assertEquals(
				'name="test" foo="bar"',
				$this->object->arrayToAttributes(array(
					'name' => 'test',
					'foo' => 'bar',
				))
		);
	}

	/**
	 * @covers FuelPHP\Common\Html::arrayToAttributes
	 */
	public function testArrayToAttributesSingle()
	{
		$this->assertEquals(
				'name="test"',
				$this->object->arrayToAttributes(array(
					'name' => 'test',
				))
		);
	}
	
	/**
	 * @covers FuelPHP\Common\Html::arrayToAttributes
	 */
	public function testArrayToAttributesEmpty()
	{
		$this->assertEquals(
				'',
				$this->object->arrayToAttributes(array())
		);
	}
	
}
