<?php

namespace Fuel\Common;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-25 at 17:46:44.
 */
class PaginationTest extends \PHPUnit_Framework_TestCase
{
		public function testDummy()
		{
//			$x = new Pagination();
		}

}
