<?php

namespace Fuel\Common;

use Codeception\TestCase\Test;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-25 at 17:46:44.
 */
class DateRangeTest extends Test
{

	/**
	 * @covers Fuel\Common\DateRange::offsetExists
	 * @covers Fuel\Common\DateRange::offsetGet
	 * @group Common
	 */
	public function testArrayAccess()
	{
		$iso = 'R4/2012-07-01T00:00:00Z/P7D';
		$period = new DateRange($iso);

		$this->assertEquals($period[0]->format('Y-m-d'), '2012-07-01');
		$this->assertEquals($period[4]->format('Y-m-d'), '2012-07-29');
		$this->assertTrue(isset($period[0]));
		$this->assertTrue(isset($period[4]));
		$this->assertFalse(isset($period[5]));
		$this->assertNull($period[5]);
	}

	/**
	 * @covers Fuel\Common\DateRange::offsetSet
	 * @expectedException  \RuntimeException
	 * @group Common
	 */
	public function testArrayAccessSet()
	{
		$iso = 'R4/2012-07-01T00:00:00Z/P7D';
		$period = new DateRange($iso);

		$period[10] = 'this is an exception';
	}

	/**
	 * @covers Fuel\Common\DateRange::offsetUnset
	 * @expectedException  \RuntimeException
	 * @group Common
	 */
	public function testArrayAccessUnset()
	{
		$iso = 'R4/2012-07-01T00:00:00Z/P7D';
		$period = new DateRange($iso);

		unset($period[10]);
	}
}
