<?php

namespace FuelPHP\Common\Table\Render;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-25 at 15:51:45.
 */
class SimpleTableTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var SimpleTable
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new SimpleTable;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}
	
	public function testRender()
	{
		$table = new \FuelPHP\Common\Table();
		$table
			->addCell('foo')
			->addCell('bar')
			->addRow();
		
		$expected = '<table><thead></thead><tbody><tr><td>foo</td><td>bar</td></tr></tbody><tfoot></tfoot></table>';
		
		$result = $this->object->renderTable($table);
		
		$this->assertXmlStringEqualsXmlString(
			$expected, 
			$result
		);
	}

}
