<?php

namespace FuelPHP\Common;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-25 at 17:46:44.
 */
class TableBuilderTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var TableBuilder
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new TableBuilder;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
		
	}
	
	/**
	 * @covers FuelPHP\Common\TableBuilder::getCurrentRow
	 * @group common
	 */
	public function testGetCurrentRow()
	{
		$this->assertInstanceOf(
				'FuelPHP\Common\TableBuilder\Row',
				$this->object->getCurrentRow()
		);
	}
	
	/**
	 * @covers FuelPHP\Common\TableBuilder::getRows
	 * @group common
	 */
	public function testGetRowsEmpty()
	{
		$this->assertEquals(0, count($this->object->getRows()));
	}
	
	/**
	 * @covers FuelPHP\Common\TableBuilder::getRows
	 * @covers FuelPHP\Common\TableBuilder::addRow
	 * @group common
	 */
	public function testAddRow()
	{
		$rowCount = 10;
		
		for ($i=0; $i < $rowCount; $i++)
		{
			$this->object->addRow();
		}
		
		$this->assertEquals($rowCount, count($this->object->getRows()));
	}
	
	/**
	 * @covers FuelPHP\Common\TableBuilder::addCell
	 * @covers FuelPHP\Common\TableBuilder::getCurrentRow
	 * @group common
	 */
	public function testAddCellContent()
	{
		$this->object->addCell('This is some content');
		
		$this->assertEquals(
				1,
				count($this->object->getCurrentRow())
		);
	}
	
	/**
	 * @covers FuelPHP\Common\TableBuilder::addCell
	 * @covers FuelPHP\Common\TableBuilder::getCurrentRow
	 * @group common
	 */
	public function testAddCell()
	{
		$this->object->addCell(new TableBuilder\Cell('This is some content'));
		
		$this->assertEquals(
				1,
				count($this->object->getCurrentRow())
		);
	}

}
